---
title: 'Where to place TLS plots in BCI: (1b) calculate quadrat-level canopy height statistics'
author: "Helene Muller-Landau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r install-packages}
# list of package dependencies
req_packages <- c("tiff","fields")

# packages that are not yet installed on the computer
ins_packages <-  req_packages[!(req_packages %in% rownames(installed.packages()))]

# install missing packages
if (length(ins_packages) > 0) 
  install.packages(ins_packages)

for (i in 1:length(req_packages))
  require(req_packages[i],character.only=T)
```


```{r read-canht-tiff}
lidar2023in <- readTIFF("canht/DEM_lidar_airborne_50ha_CHM.tif")
lidar2023in[lidar2023in== -32767] <- NA
lidar2023rev2 <- t(apply(lidar2023in,2,rev))
#xs <- seq(-20,1020,length=dim(lidar2023in)[2])
#ys <- seq(-20,520,length=dim(lidar2023in)[1])

#image.plot(xs,ys,lidar2023t,col=heat.colors(20),main="Transpose only")
#image.plot(xs,ys,lidar2023rev1,col=heat.colors(20),main="Rev 1 only")
#image.plot(xs,ys,lidar2023rev2,col=heat.colors(20),main="transpose(rev2)")
#image.plot(xs,ys,lidar2023rev2,col=heat.colors(20),main="Lidar canopy height May 2023",xlab="",ylab="")
```



```{r canhtlidar2}

nx <- dim(lidar2023rev2)[1]
ny <- dim(lidar2023rev2)[2]
xint <- 1040/nx
yint <- 540/ny
xs <- seq(-20+xint,1020-xint,length=nx)
ys <- seq(-20+yint,520-yint,length=ny)

image(xs,ys,lidar2023rev2,col=heat.colors(20),main="Lidar canopy height May 2023",xlab="",ylab="")
lines(c(0,0,1000,1000,0),c(0,500,500,0,0))
lines(c(-20,-20,1020,1020,-20),c(-20,520,520,-20,-20))


```

### Get 20-m means and sds of canopy height


```{r getmatrixmeansd}
# function to obtain quadrat-level means and sds
# of one input matrix as two output matrices 
# with each cell holding the mean or sd of the original matrix cells 
# within the specified quadrat 
getmatrixmeansd2 <- function (inmatrix,inxcenters,inycenters,
                              outxcenters=seq(-10,1010,by=20),outycenters=seq(-10,510,by=20)) {
  innrowm <- length(inxcenters)
  inncolm <- length(inycenters)
  nrowm <- length(outxcenters)
  ncolm <- length(outycenters)
  xoutsidedist <- outxcenters[2]-outxcenters[1]
  youtsidedist <- outycenters[2]-outycenters[1]
  mnoutmatrix <- sdoutmatrix <- matrix(NA, nrow=nrowm,ncol=ncolm)
  minxis <- maxxis <- rep(NA, nrowm)
  minyis <- maxyis <- rep(NA, ncolm)
  for (i in 1:nrowm) {
    minxis[i] <- min(seq(1,innrowm)[inxcenters>outxcenters[i]-xoutsidedist/2])
    maxxis[i] <- max(seq(1,innrowm)[inxcenters<outxcenters[i]+xoutsidedist/2])
  }
  for (j in 1:ncolm) {
    minyis[j] <- min(seq(1,inncolm)[inycenters>outycenters[j]-youtsidedist/2])
    maxyis[j] <- max(seq(1,inncolm)[inycenters<outycenters[j]+youtsidedist/2])
  }
  for (i in 1:nrowm) {
    for (j in 1:ncolm) {
      thism <- inmatrix[minxis[i]:maxxis[i],minyis[j]:maxyis[j]]
      mnoutmatrix[i,j] <- mean(thism,na.rm=T)
      sdoutmatrix[i,j] <- sd(thism,na.rm=T)
    }
  }
  return(list(mnmatrix=mnoutmatrix,sdmatrix=sdoutmatrix))
}
```

Obtain the quadrat-level means and sds for 20-m and 5-m quadrats.  
```{r getquadratmnsdcanht}
outx20 <- seq(-10,1010,by=20)
outy20 <- seq(-10,510,by=20)
stats20m <- getmatrixmeansd2(lidar2023rev2,xs,ys,outxcenters=outx20,outycenters=outy20)
mean20m <- stats20m$mnmatrix
sd20m <- stats20m$sdmatrix

outx5 <- seq(-17.5,1017.5, by=5)
outy5 <- seq(-17.5,517.5,by=5)
stats5m <- getmatrixmeansd2(lidar2023rev2,xs,ys,outxcenters=outx5,
                            outycenters=outy5)
mean5m <- stats5m$mnmatrix
sd5m <- stats5m$sdmatrix

q20df <- data.frame(x=rep(outx20,length(outy20)),y=rep(outy20,times=length(outx20)),
                    mncanht2023=as.vector(mean20m),sdcanht2023=as.vector(sd20m))
p5df <- data.frame(x=rep(outx5,length(outy5)),y=rep(outy5,times=length(outx5)),
                    mncanht2023=as.vector(mean5m),sdcanht2023=as.vector(sd5m))

write.table(q20df,file="usedata/canht2023q20.txt",row.names=F,sep="\t")
write.table(p5df,file="usedata/canht2023p5.txt",row.names=F,sep="\t")
```

Make figures of the canopy height maps.  
```{r}
image.plot(outx20,outy20,mean20m,col=heat.colors(20),
           main="20-m Mean Lidar canopy height May 2023",xlab="",ylab="")
lines(c(0,0,1000,1000,0),c(0,500,500,0,0))
image.plot(outx20,outy20,sd20m,col=heat.colors(20),
           main="20-m SD Lidar canopy height May 2023",xlab="",ylab="")
lines(c(0,0,1000,1000,0),c(0,500,500,0,0))
image.plot(outx5,outy5,sd5m,col=heat.colors(20),
           main="5-m SD Lidar canopy height May 2023",xlab="",ylab="")
lines(c(0,0,1000,1000,0),c(0,500,500,0,0))
image.plot(outx5,outy5,mean5m,col=heat.colors(20),
           main="5-m Mean Lidar canopy height May 2023",xlab="",ylab="")
lines(c(0,0,1000,1000,0),c(0,500,500,0,0))
```


Function to do running means of matrices. 

```{r getmatrixrunmean}
# function to return a matrix of the same dimensions as the input
# with each cell holding the mean of the original matrix cells 
# centered on the current cell and with row and column difference <= sidedist
# so for example, sidedist=1 would mean a mean of a 3x3 unit centered on the focal one
getmatrixrunmean <- function (inmatrix,sidedist=2) {
  nrowm <- dim(inmatrix)[1]
  ncolm <- dim(inmatrix)[2]
  outmatrix <- matrix(NA, nrow=nrowm,ncol=ncolm)
  for (i in 1:nrowm) {
    for (j in 1:ncolm) {
      thism <- inmatrix[(max(1,i-sidedist):min(nrowm,i+sidedist)),(max(1,j-sidedist):min(ncolm,j+sidedist))]
      outmatrix[i,j] <- mean(thism)
    }
  }
  return(outmatrix)
}
```




Load the 20-m lidar-derived canopy height stats archived with Schnitzer et al. 2021. (Downloaded in whereTLSonBCI_part1.Rmd)

```{r canhtlidarolder}
lidar20 <- read.csv("liana/lidar_20_20.csv",header=T) #lidar-based canopy heights in 2 dates for each 20x20 
lidar20 <- lidar20[order(lidar20$y,lidar20$x),]
xs <- sort(unique(lidar20$x))
ys <- sort(unique(lidar20$y))

lidar2009 <- matrix(lidar20$H2009,nrow=length(xs),ncol=length(ys))
#image.plot(xs,ys,lidar2009,main="Lidar canopy Height 2009",col=heat.colors(30),xlab="",ylab="")
image.plot(xs,ys,lidar2009,main="20-m Lidar canopy Height 2009",col=heat.colors(30),xlab="",ylab="")

lidar2019 <- matrix(lidar20$H2019,nrow=length(xs),ncol=length(ys))
#image.plot(xs,ys,lidar2019,main="Lidar canopy Height 2019",col=heat.colors(30),xlab="",ylab="")
image.plot(xs,ys,lidar2019,main="20-m Lidar canopy Height 2019",col=heat.colors(30),xlab="",ylab="")

```
